### ISSUE TITLE
Transition polish/fixes/todolist

### ISSUE THREAD

**Issue by d-j-a-y** [game-stop/veejay#266]
* FIXME duplicated signals fix - see gtkadjustement (shared GtkAdjustment for the Shape value and not shared for Lenght ?) - af9e307 

* FIXME  transitioning from sample to stream |ESC| act strange :
   * From sample to stream, the transition shape and time come from stream properties (should be sample properties) - 3c51a72
   * From stream to sample, shape and length coming from .... ? - 3c51a72 
   * From stream to sample, seems it's transitioning over himself? 
   * From stream to sample (with multiple streams) ,sample problem with length (shape?) values 

* FIXME when transition is activated the thumbnail in reloaded became not revelant

* FIXME reloaded / when minus on length == 1 ---> send 0 but updated in GUI to 25 - i suspect a bad value comming from server?

* FIXME reloaded / at startup, transition properties are not revelant. (shift-T the properties does'n update in GUI)

* FIXME doc!

* CHECKME  stream <-> sample; stream appear without fx chain

* CHECKME high sample speed, transition problem ? 

* FEATURE  add key for activate by slot (speed / length)

* FEATURE sound transitioning (see #258)

**Comment by c0ntrol** [comment]
I need to retest this
