### ISSUE TITLE
libveejaycore-1.5.so.0: not found

### ISSUE THREAD

**Issue by hellocatfood** [game-stop/veejay#279]
I have installed all of the parts of veejay on Ubuntu 23.10. When I run `veejay` it fails with the following error:

```
veejay: error while loading shared libraries: libveejaycore-1.5.so.0: cannot open shared object file: No such file or directory
```

**Comment by game-stop** [comment]
Hi, please run 'sudo ldconfig' after make install so the library cache is updated with the newly installed library

**Comment by hellocatfood** [comment]
Thanks, that worked!
